// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spb-t4nue4dp4m51lg7d.supabase.opentrust.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG51ZTRkcDRtNTFsZzdkIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzY2ODc5MDcsImV4cCI6MjA5MjI2MzkwN30.PJXc3JAeBJ9-D9lBPegYXrkAmJx3Ef1OQfsql7SG7qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
